# frozen_string_literal: true

module Kettle
  module Jem
    module Appraisals
      # Generates the +Appraisals+ file content from the computed matrix.
      #
      # Each appraisal entry uses +eval_gemfile+ to compose its modular gemfiles
      # (tier1, optional tier2, and +x_std_libs+).
      #
      # @example
      #   content = AppraisalsGenerator.generate(matrix_entries)
      #   File.write("Appraisals", content)
      class AppraisalsGenerator
        class << self
          # Generates the full +Appraisals+ file content as a String.
          #
          # @param matrix [Array<Hash>] each entry must have the keys:
          #   * +:name+ — the appraisal name (e.g., +"kja-ar-7-1-r3"+)
          #   * +:tier1_gemfile+ — relative path to the tier1 modular gemfile
          #   * +:tier2_gemfile+ — relative path to the tier2 modular gemfile (or +nil+)
          #   * +:x_std_libs_gemfile+ — relative path to the x_std_libs gemfile
          #   * +:ruby_series+ — the Ruby series bucket name
          # @return [String] the complete Appraisals file content
          def generate(matrix)
            lines = [
              "# frozen_string_literal: true",
              "",
              "# Generated by kettle-jem-appraisals",
              "# Do not edit directly — re-run `kettle-jem-appraisals --resolve` to regenerate.",
              "",
            ]

            matrix.each do |entry|
              lines << "appraise #{entry[:name].inspect} do"
              lines << "  eval_gemfile #{entry[:tier1_gemfile].inspect}" if entry[:tier1_gemfile]
              lines << "  eval_gemfile #{entry[:tier2_gemfile].inspect}" if entry[:tier2_gemfile]
              lines << "  eval_gemfile #{entry[:x_std_libs_gemfile].inspect}" if entry[:x_std_libs_gemfile]
              lines << "end"
              lines << ""
            end

            "#{lines.join("\n")}\n"
          end
        end
      end
    end
  end
end
