# frozen_string_literal: true

module Kettle
  module Jem
    module Appraisals
      # Generates the Appraisals file content from the computed matrix.
      # Each appraisal entry eval_gemfiles its modular gemfiles.
      class AppraisalsGenerator
        # Generates the Appraisals file content.
        # @param matrix [Array<Hash>] each entry:
        #   { name: "ar-7-1-oa-2-1-r3",
        #     tier1_gemfile: "gemfiles/modular/activerecord/r3/v7.1.gemfile",
        #     tier2_gemfile: "gemfiles/modular/omniauth/r3/v2.1.gemfile",
        #     x_std_libs_gemfile: "gemfiles/modular/x_std_libs/r3/libs.gemfile",
        #     ruby_series: "r3" }
        # @return [String] Appraisals file content
        def self.generate(matrix)
          lines = [
            "# frozen_string_literal: true",
            "",
            "# Generated by kettle-jem-appraisals",
            "# Do not edit directly — re-run `kettle-jem-appraisals --resolve` to regenerate.",
            "",
          ]

          matrix.each do |entry|
            lines << "appraise #{entry[:name].inspect} do"
            lines << "  eval_gemfile #{entry[:tier1_gemfile].inspect}" if entry[:tier1_gemfile]
            lines << "  eval_gemfile #{entry[:tier2_gemfile].inspect}" if entry[:tier2_gemfile]
            lines << "  eval_gemfile #{entry[:x_std_libs_gemfile].inspect}" if entry[:x_std_libs_gemfile]
            lines << "end"
            lines << ""
          end

          "#{lines.join("\n")}\n"
        end
      end
    end
  end
end
