# frozen_string_literal: true

module Kettle
  module Jem
    module Appraisals
      # Generates modular gemfile files for the appraisal matrix.
      # Creates files like: gemfiles/modular/activerecord/r3/v7.1.gemfile
      class ModularGemfileGenerator
        attr_reader :base_dir

        # @param base_dir [String] path to the project root (where gemfiles/ lives)
        def initialize(base_dir: Dir.pwd)
          @base_dir = base_dir
        end

        # Generates a modular gemfile for a tier1 gem at a given version and ruby series.
        # @param gem_name [String] e.g., "activerecord"
        # @param version [String] e.g., "7.1"
        # @param ruby_series [String] e.g., "r3"
        # @param sub_deps [Hash] e.g., {"sqlite3" => "1.6.9"}
        # @return [String] the relative path to the generated gemfile
        def generate(gem_name:, version:, ruby_series:, sub_deps: {})
          dir = File.join(base_dir, "gemfiles", "modular", gem_name, ruby_series)
          FileUtils.mkdir_p(dir)

          filename = "v#{version}.gemfile"
          path = File.join(dir, filename)
          content = build_content(gem_name, version, sub_deps)

          File.write(path, content)
          File.join("gemfiles", "modular", gem_name, ruby_series, filename)
        end

        # Generates a tier2 modular gemfile.
        # @param gem_name [String] e.g., "omniauth"
        # @param version [String] e.g., "2.1"
        # @param ruby_series [String] e.g., "r3"
        # @return [String] the relative path
        def generate_tier2(gem_name:, version:, ruby_series:)
          dir = File.join(base_dir, "gemfiles", "modular", gem_name, ruby_series)
          FileUtils.mkdir_p(dir)

          filename = "v#{version}.gemfile"
          path = File.join(dir, filename)
          content = build_tier2_content(gem_name, version)

          File.write(path, content)
          File.join("gemfiles", "modular", gem_name, ruby_series, filename)
        end

        private

        def build_content(gem_name, version, sub_deps)
          lines = [
            "# frozen_string_literal: true",
            "",
            "# Generated by kettle-jem-appraisals",
            "gem #{gem_name.inspect}, \"~> #{version}.0\"",
          ]

          sub_deps.each do |dep_name, dep_version|
            lines << "gem #{dep_name.inspect}, \"~> #{dep_version}\""
          end

          lines << ""
          "#{lines.join("\n")}\n"
        end

        def build_tier2_content(gem_name, version)
          lines = [
            "# frozen_string_literal: true",
            "",
            "# Generated by kettle-jem-appraisals",
            "gem #{gem_name.inspect}, \"~> #{version}.0\"",
            "",
          ]
          "#{lines.join("\n")}\n"
        end
      end
    end
  end
end
